import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :arcada, ArcadaWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Redirect any http request to https and emit HSTS. `rewrite_on:
  # [:x_forwarded_proto]` trusts the Cloudflare → Traefik chain's scheme header
  # (TLS terminates at the edge; the app receives http with x-forwarded-proto:
  # https), so this must NOT be enabled unless the origin only sees proxied
  # traffic — the `cloudflare-only` origin lock guarantees that.
  force_ssl: [rewrite_on: [:x_forwarded_proto], hsts: true]

# Mark session + remember-me cookies Secure (HTTPS-only) in production. Read at
# compile time by the cookie option lists in ArcadaWeb.Endpoint / ArcadaWeb.UserAuth.
config :arcada, :secure_cookies, true

# Do not print debug messages in production
config :logger, level: :info

# Structured JSON logs to stdout, consistent with the other Dokploy apps —
# Alloy ships the container's stdout to Loki, where `| json` parses these
# fields (severity, message, request_id, …). The Basic formatter emits one
# JSON object per line: %{time, severity, message, metadata}.
config :logger, :default_handler,
  formatter:
    {LoggerJSON.Formatters.Basic,
     metadata: [:request_id, :mfa, :file, :line, :crash_reason, :domain]}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
